image: golang:1.10
stages:
  - build

variables:
  SRCDIR: /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  GOBIN: $SRCDIR/artifacts

before_script:
  - echo $(env)
  - ln -s /builds /go/src/gitlab.com
  - cd $SRCDIR
  - go get
  - go install
  - ls -alh

build-pingviz:
  stage: build
  script:
    - go get
    - go install
