image: golang:1.10
stages:
  - build

variables:
  SRCDIR: /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  ARTIFACTDIR: release
  GOBIN: /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/release


before_script:
  - ln -s /builds /go/src/gitlab.com

pingviz-release:
  stage: build
  script:
    - cd $SRCDIR
    - go get
    - go install

  artifacts:
    paths:
      - $ARTIFACTDIR/*
