image: golang:1.10
stages:
  - build

variables:
  SRCDIR: /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME
  ARTIFACTDIR: artifacts
  GOBIN: /go/src/gitlab.com/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/artifacts


before_script:
  - echo $(env)
  - ln -s /builds /go/src/gitlab.com

build-pingviz:
  stage: build
  script:
    - cd $SRCDIR
    - go get
    - go install
    - ls -alh

  artifacts:
    paths:
      - $ARTIFACTDIR/*
